=== faros-ai/airbyte-connectors/sources/bitbucket-source/resources/schemas/workspaces.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "uuid": {
      "type": "string",
      "format": "uuid"
    },
    "links": {
      "type": "object",
      "properties": {
        "ownersUrl": {
          "type": "string",
          "format": "uri"
        },
        "repositoriesUrl": {
          "type": "string",
          "format": "uri"
        },
        "htmlUrl": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "createdOn": {
      "type": "string",
      "format": "date-time"
    },
    "type": {
      "type": "string"
    },
    "slug": {
      "type": "string"
    },
    "isPrivate": {
      "type": "boolean"
    },
    "name": {
      "type": "string"
    }
  }
}

=== faros-ai/airbyte-connectors/sources/bitbucket-source/test_files/workspaces-response.json
[
  {
    "uuid": "{25336f4e-358d-4ba6-afb9-f8d25284ecaf}",
    "createdOn": "2020-12-08T18:52:43.318039+00:00",
    "type": "workspace",
    "slug": "YulyKo",
    "isPrivate": false,
    "name": "Yulia Kotenko",
    "links": {
      "ownersUrl": "https://api.bitbucket.org/2.0/workspaces/YulyKo/members?q=permission%3D%22owner%22",
      "repositoriesUrl": "https://api.bitbucket.org/2.0/repositories/YulyKo",
      "htmlUrl": "https://bitbucket.org/YulyKo/"
    }
  },
  {
    "uuid": "{f3e031ff-0dac-41be-898d-43074686fd59}",
    "createdOn": "2018-12-01T19:48:25.598862+00:00",
    "type": "workspace",
    "slug": "objectivemax",
    "isPrivate": false,
    "name": "objectivemax",
    "links": {
      "ownersUrl": "https://api.bitbucket.org/2.0/workspaces/objectivemax/members?q=permission%3D%22owner%22",
      "repositoriesUrl": "https://api.bitbucket.org/2.0/repositories/objectivemax",
      "htmlUrl": "https://bitbucket.org/objectivemax/"
    }
  },
  {
    "uuid": "{46e585e0-6f39-42f1-adc3-e234e729afea}",
    "createdOn": "2019-10-03T09:58:16.801151+00:00",
    "type": "workspace",
    "slug": "RomanKyrnis",
    "isPrivate": false,
    "name": "Roman Kirnos",
    "links": {
      "ownersUrl": "https://api.bitbucket.org/2.0/workspaces/RomanKyrnis/members?q=permission%3D%22owner%22",
      "repositoriesUrl": "https://api.bitbucket.org/2.0/repositories/RomanKyrnis",
      "htmlUrl": "https://bitbucket.org/RomanKyrnis/"
    }
  }
]
