=== faros-ai/airbyte-connectors/sources/statuspage-source/resources/schemas/components.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "page_id": {
      "type": "string"
    },
    "group_id": {
      "type": [
        "string",
        "null"
      ]
    },
    "created_at": {
      "type": "string"
    },
    "updated_at": {
      "type": "string"
    },
    "group": {
      "type": "boolean"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": [
        "string",
        "null"
      ]
    },
    "position": {
      "type": "integer"
    },
    "status": {
      "type": "string"
    },
    "showcase": {
      "type": "boolean"
    },
    "only_show_if_degraded": {
      "type": "boolean"
    },
    "automation_email": {
      "type": "string"
    },
    "start_date": {
      "type": [
        "string",
        "null"
      ]
    }
  }
}

=== faros-ai/airbyte-connectors/sources/statuspage-source/test_files/components.json
[
  {
    "id": "component1",
    "page_id": "string",
    "group_id": "string",
    "created_at": "2023-05-22T13:42:58Z",
    "updated_at": "2023-05-22T13:42:58Z",
    "group": true,
    "name": "string",
    "description": "string",
    "position": 0,
    "status": "operational",
    "showcase": true,
    "only_show_if_degraded": true,
    "automation_email": "string",
    "start_date": "2023-05-22"
  },
  {
    "id": "component2",
    "page_id": "string",
    "group_id": "string",
    "created_at": "2023-05-22T13:42:58Z",
    "updated_at": "2023-05-22T13:42:58Z",
    "group": true,
    "name": "string",
    "description": "string",
    "position": 0,
    "status": "operational",
    "showcase": true,
    "only_show_if_degraded": true,
    "automation_email": "string",
    "start_date": "2023-05-22"
  }
]
