=== faros-ai/airbyte-connectors/sources/squadcast-source/resources/schemas/events.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": true,
  "properties": {
    "incident_id": {
      "type": "string"
    },
    "alert_source_id": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "time_of_creation": {
      "type": "string"
    },
    "tags": {
      "type": "object",
      "patternProperties": {
        ".": {
          "value": {
            "type": "string"
          },
          "color": {
            "type": "string"
          }
        }
      }
    },
    "deduplication_reason": {
      "type": "object",
      "properties": {
        "matched_event_id": {
          "type": "string"
        },
        "evaluated_expression": {
          "type": "string"
        },
        "time_window": {
          "type": "string"
        }
      }
    },
    "payload": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "event_id": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "metric": {
          "type": "object",
          "properties": {
            "absolute": {
              "type": "object",
              "properties": {
                "current_value": {
                  "type": "number"
                },
                "threshold": {
                  "type": "number"
                },
                "unit": {
                  "type": "string"
                }
              }
            },
            "pod": {
              "type": "string"
            },
            "relative": {
              "type": "object",
              "properties": {
                "current_value": {
                  "type": "number"
                },
                "threshold": {
                  "type": "number"
                }
              }
            },
            "time": {
              "type": "string"
            }
          }
        },
        "status": {
          "type": "string"
        },
        "assignee": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          }
        },
        "created_by": {
          "type": "string"
        },
        "tags": {
          "type": "object",
          "patternProperties": {
            ".": {
              "value": {
                "type": "string"
              },
              "color": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}

=== faros-ai/airbyte-connectors/sources/squadcast-source/test_files/events.json
[
  {
    "incident_id": "619cb810f88b5d9a2ab1271d",
    "alert_source_id": "5fae6d03ef87d3896aa92ad1",
    "message": "Faros-test",
    "description": "incident",
    "time_of_creation": "2021-11-23T09:44:48.891Z",
    "tags": {
      "teg": {
        "value": "value",
        "color": "#00A96B"
      }
    },
    "payload": {
      "assignee": {
        "id": "619cb17408e88c8a8acdf394",
        "type": "escalationpolicy"
      },
      "created_by": "619cb1620a326c0008d59b51",
      "description": "incident",
      "message": "Faros-test",
      "tags": {
        "teg": {
          "color": "#00A96B",
          "value": "value"
        }
      },
      "status": "resolved"
    }
  }
]
